/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tujuh */

#ifndef _Included_tujuh
#define _Included_tujuh
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
